const JoiHeb = [];
JoiHeb["any.empty"] = 'שדה ריק';
JoiHeb['string.email'] = 'הכנס אימייל תקני';
JoiHeb['string.min'] = 'הוסף תוים נוספים' ;
JoiHeb['string.alphanum'] = 'אותיות ומספרים בלבד' ; 
JoiHeb['email.taken'] = 'אימייל תפוס';
JoiHeb['server404'] = 'בעיית התחברות לשרת';
JoiHeb['auth400'] = 'נתונים שגויים';
JoiHeb['btnLogin']='התחבר';
export default JoiHeb;